name: EquipesRosaire
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  webview_flutter: ^4.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.16
  intl: ^0.18.0
  url_launcher: ^6.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:  
    - assets/EDR-logo-blanc.png

flutter_icons:
  image_path: "assets/EdR_icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/EdR_splash.png
  android_12:
   image: assets/EdR_splash.png

